### ISSUE TITLE
主题建议添加一个暗黑主题，感觉更加炫酷

### ISSUE THREAD

**Issue by YoungWilliamZ** [imxieyi/sushelper_feedback#1]
打开发现没有黑白主题很失落

**Comment by imxieyi** [comment]
正好最近要发更新。我会尝试加一个黑色主题，关于前景色和背景色如果你有什么建议欢迎提出来。

**Comment by imxieyi** [comment]
最后效果可能不太好，因为很多地方是按照亮色主题做的，不太容易修改。

**Comment by YoungWilliamZ** [comment]
灰色当背景，黑色当主色调？然后不变的黄色改一改，白色？

**Comment by imxieyi** [comment]
关于具体颜色你有什么建议吗？用HTML颜色格式就行。
